In [27]:
import torch
import numpy as np

In [ ]:
# initialize a Tensor
# from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

print(x_data)
print(type(x_data))
print(x_data.shape)
print(x_data.dtype)

# from a numpy array
np_array = np.array(data)
x_np_ten = torch.from_numpy(np_array)

print(x_np_ten)

# from other tensors
x_ones = torch.ones_like(x_data) # retains properties of origin and filled with ones
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # fills random numbers 0-1 but need to change data type
print(f"Random Tensor:\n {x_rand} \n")

# by giving the dimensions and fill values random or with constants
shape = (2,3)       # dimensions
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor}\n")
print(f"Ones Tensor: \n {ones_tensor}\n")
print(f"Zeros Tensor: \n {zeros_tensor}")

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
torch.Size([2, 2])
torch.int64
tensor([[1, 2],
        [3, 4]])
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor:
 tensor([[0.1294, 0.1122],
        [0.6742, 0.9943]]) 

Random Tensor: 
 tensor([[0.9254, 0.5424, 0.3614],
        [0.4894, 0.1001, 0.3471]])

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [29]:
# attributes of a Tensor
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}\n")
print(f"Datatype of tensor: {tensor.dtype}\n")
print(f"Device tensor is stored on: {tensor.device}\n")

Shape of tensor: torch.Size([3, 4])

Datatype of tensor: torch.float32

Device tensor is stored on: cpu



In [ ]:
# operations on Tensors
# move the tensor to a accelerator/GPU for saving time and memory
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

# numpy-like indexing and slicing:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}\n")
print(f"First column: {tensor[:, 0]}\n")
tensor[:,1] = 0         # override second column
print(tensor)

# concatenate a set of tensors along a given dimension
t1 = torch.cat([tensor, tensor, tensor], dim = 1)       # dim 1 is line
t2 = torch.cat([tensor, tensor, tensor], dim = 0)       # dim 0 is column

print(t1)
print(t2)

# arithmetic operations
    # matrix multiplication between two tensors --> y1, y2 & y3 are matrix multiplication in similar ways
        # tensor.T returns transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

    # element wise product --> z1, z2 & z3 are similar ways
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

# convert single value tensor to a Python numerical value using item()
agg = tensor.sum()      # aggregate tensor
agg_item = agg.item()
print(agg_item, type(agg_item))

# in-place operations --> operations on the same element --> recognize by "_" at the end
    # --> do not use when planning on Autograd
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

First row: tensor([1., 1., 1., 1.])

First column: tensor([1., 1., 1., 1.])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
12.0 <class 'float'>
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [35]:
# Bridge to numpy --> Tensors (on CPU) and numpy-arrays can share memory
# a change on one of them will affect the other

    # tensor to numpy-array
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)       # change affects both
print(f"t: {t}")
print(f"n: {n}")

    # numpy-array to tensor
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
